language: node_js
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'
  - '9'
  - '8'
  - '6'
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
before_deploy:
  - cd www; npm install && npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: www/public
  on:
    branch: master
