language: node_js
cache: yarn
notifications:
  email: false
node_js:
  - '11'
  - '10'
  - '9'
  - '8'

jobs:
  include:
    - stage: npm release
      if: branch = master AND type = push
      node_js: "10"
      skip_cleanup: true
      script: echo "Deploying to npm ..."
      script: yarn run semantic-release
    - stage: GitHub Pages
      if: branch = master AND type = push
      node_js: "10"
      script: cd www; yarn && yarn run build
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GH_TOKEN
        keep-history: true
        local-dir: www/public
        on:
          branch: master
          node: '10'
