language: node_js
cache: yarn
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
notifications:
  email: false
node_js:
  - '11'
  - '10'
  - '9'
  - '8'

jobs:
  include:
    - stage: npm release
      node_js: "10"
      script: echo "Deploying to npm ..."
      script: yarn run build
      script: yarn run semantic-release
    - stage: GitHub Pages
      script: cd www; yarn && yarn run build
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GH_TOKEN
        keep-history: true
        local-dir: www/public
        on:
          branch: master
          node: '10'
